site_name: OpenComs
theme: readthedocs

nav:
    - Home: index.md
    - Analog systems:
        - analog/introduction.md
        - analog/technical-details.md
        - Devices:
            - ABP1 (Beltpack 1): analog/devices/abp1/docs.md
            - APSM1 (Power supply module 1): analog/devices/apsm1/docs.md
    - Digital systems: []
