name: build

permissions:
  pull-requests: write
  deployments: write
  repository-projects: write
  contents: write
  pages: write
  
  
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
