name: build

permissions:
  pull-requests: write
  deployments: write
  repository-projects: write
  contents: write
  pages: write
  
  
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - run: pip install mkdocs
      
      - run: mkdocs gh-deploy --force --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
